services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_db
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - GEMINI_API_KEY=AIzaSyDiTf_auB_xigiycG6sOcBaJ0zrHxiQBO8
      - SYSTEM_PROMPT=You are a helpful, friendly, and professional legal assistant specializing in Indian law. You may respond to greetings and small talk briefly. For legal questions, provide detailed analysis based on provided context. If information is not available, say 'I don't know' rather than guessing.
    volumes:
      - ./index:/app/index
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./my-app
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:80"

volumes:
  postgres_data:
